### ISSUE TITLE
Invisible plot when using colors

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence2#15]
See reprex below:

``` r
library(magrittr)
library(incidence2)

outbreaks::ebola_sim_clean$linelist %>%
  incidence(date_of_onset, groups = outcome) %>%
  plot()
#> The number of colors (1) did not match the number of groups (3).
#> Using `col_pal` instead.
```

![](https://i.imgur.com/mdNaV6d.png)

It may come from the borders ie bars are so thin we see only the border? Plot is fine with wider time intervals.

<sup>Created on 2020-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tjtnew** [comment]
This should be fixed in the [plot](https://github.com/reconhub/incidence2/tree/plots) branch.  Examples of new branch behaviour:

``` r
library(incidence2)

data(ebola_sim_clean, package = "outbreaks")
dat <- ebola_sim_clean$linelist

# invisible issue fixed
dat %>%
  incidence(date_of_onset, groups = outcome) %>%
  plot()
```

![](https://i.imgur.com/MF3Pcee.png)

``` r


# group by three groups
inci <- incidence(dat,
                  date_index = date_of_onset,
                  interval = 7,
                  groups = c(hospital, gender, outcome))

# message if you try to plot by more than one group (output plot is then regrouped)
plot(inci)
#> Note - plotting by date only:
#>  * `plot` can only stack/dodge by one variable.
#>  * Please `regroup` the object to one variable or use `facet_plot`.
```

![](https://i.imgur.com/WbFAWOM.png)

``` r

# same output as above but no message
plot(inci, group = FALSE)
```

![](https://i.imgur.com/lIIhCcK.png)

``` r

# NA now grey (default stacked plot)
inci %>% 
  regroup(outcome) %>% 
  plot()
```

![](https://i.imgur.com/s45h8Qt.png)

``` r

# dodge plot
inci %>% 
  regroup(outcome) %>% 
  plot(stack = FALSE)
```

![](https://i.imgur.com/flAM9P6.png)

``` r

# facet plot
inci %>%
  regroup(c(gender, outcome)) %>% 
  facet_plot(n_breaks = 3)
```

![](https://i.imgur.com/ygnegqV.png)

``` r

# facet plot with legend (coloured by hospital)
inci %>%
  regroup(c(gender, hospital)) %>% 
  facet_plot(n_breaks = 3, nrow = 4, fill = hospital)
```

![](https://i.imgur.com/8sDZBXn.png)

``` r

# facet plot without legend (coloured by hospital and muted palette)
inci %>%
  regroup(c(gender, hospital)) %>% 
  facet_plot(n_breaks = 3, nrow = 4, fill = hospital, legend = FALSE, col_pal = muted)
```

![](https://i.imgur.com/ZkmMd9m.png)

<sup>Created on 2020-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thibautjombart** [comment]
This looks very good! :) 

It raises one question re using the same group for facetting and fill, as in :
```r
# facet plot with legend (coloured by hospital)
inci %>%
  regroup(c(gender, hospital)) %>% 
  facet_plot(n_breaks = 3, nrow = 4, fill = hospital)
```
I would think by default, the group used in `fill` shoud be ignored from the facetting, but can think of cases where one might want the redundancy of colors / facets. I will raise a separate issue, as this one is clearly resolved.
