### ISSUE TITLE
On the behaviour of `facet_plot`

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence2#16]
Some thoughts on how facetting may work, esp with regards to using groups for facetting and/or color-filling. Nothing hard-set, more for discussion purpose. It would be useful to have a `facet` argument handling which grouping variables are used for facetting. Together with `fill`, this should give more flexibility to the user for designing plots with different grouping variables displayed. 

Here are some proposed behaviours:

* `facet_plot(x)`: plot the incidence object using all grouping variables for facetting
* `facet_plot(x, facet = "foo")`: same, using only variable `foo` for facetting
* `facet_plot(x, facet = c(foo, bar))`: same, using variables `foo` and `bar`
* `facet_plot(x, facet = "foo", fill = bar)`: use `foo` for facetting and `bar` for filling
* `facet_plot(x, facet = c("foo", "bar"), fill = bar)`: use `foo` and `bar` for facetting, and `bar` for filling; redundant, but that's okay, the user asked for it

What do you think?

**Comment by tjtnew** [comment]
This is from the latest [plot branch](https://github.com/reconhub/incidence2/tree/plots).  I still need to provide a helper to rotate the labels on the x-axis but in terms of user interface I think the following matches with what you have above:

``` r
library(incidence2)
data(ebola_sim_clean, package = "outbreaks")
dat <- ebola_sim_clean$linelist

inci <- incidence(dat,
                  date_index = date_of_onset,
                  interval = 7,
                  groups = c(hospital, gender))


plot(inci)
#> plot() can only stack/dodge by one variable.
#> For multi-facet plotting try facet_plot()
```

![](https://i.imgur.com/4GYXqFI.png)

``` r

plot(inci, fill = gender)
#> plot() can only stack/dodge by one variable.
#> For multi-facet plotting try facet_plot()
```

![](https://i.imgur.com/5j1ijNu.png)

``` r

inci %>%
  regroup(gender) %>%
  plot(fill = gender)
```

![](https://i.imgur.com/mp1r69Y.png)

``` r

facet_plot(inci, nrow = 4)
```

![](https://i.imgur.com/24fl23Z.png)

``` r

facet_plot(inci, facets = gender)
```

![](https://i.imgur.com/FMLjyd7.png)

``` r

facet_plot(inci, facets = hospital, fill = gender, nrow = 3)
```

![](https://i.imgur.com/tCcDp86.png)

``` r

facet_plot(inci, facets = c(hospital, gender), fill = gender, nrow = 4)
```

![](https://i.imgur.com/75EwJmm.png)

<sup>Created on 2020-07-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thibautjombart** [comment]
Awesome! Yes, I think that's exactly what I had in mind :)
