### ISSUE TITLE
Adding moving average as geom_line

### ISSUE THREAD

**Issue by aspina7** [reconhub/incidence2#23]
Hey - not a must have but might be nice to have option to add a moving average line. 
This pretty commonly used on messy epi data. 
Should be quite easy to implement now that [{slider}](https://github.com/DavisVaughan/slider)  has been released. 
See [r4epi discussion](https://github.com/R4EPI/sitrep/issues/190) 

Maybe should just be left for users to so separately (i.e. add to plot themselves after)?

**Comment by tjtnew** [comment]
Sounds good.  I like the idea of

```r
dat %>% incidence() %>% plot() %>% overlay_average()
```
Would  ±2 intervals sound sensible as a default?

**Comment by aspina7** [comment]
Would generally do -2 only, as often would be running weekly reports in an outbreak. So don't want the NAs in the most recent weeks.

**Comment by tjtnew** [comment]
That makes sense.  Will add it in a dev branch (probably tomorrow) and ping you when it's there.

**Comment by tjtnew** [comment]
hhmmm... not as straightforward to integrate nicely with how I've built the plotting functions.  Need to think about this a bit more than I thought!

**Comment by tjtnew** [comment]
Hi @aspina7 
The [average](https://github.com/reconhub/incidence2/tree/average) branch as now has a rough implementation for this.  It still needs a few bit fixing but how does the following feel from a user perspective:

```r
library(outbreaks)
library(incidence2)

data(ebola_sim_clean, package = "outbreaks")
dat <- ebola_sim_clean$linelist

# incidence grouped by gender
inci <- incidence(dat,
                  date_index = date_of_onset,
                  interval = "week", 
                  last_date = "2014-10-05",
                  groups = gender)

# individual plot would needs regrouping if groups present
inci %>%  
  regroup() %>% 
  rolling_average(before = 2) %>% 
  facet_plot(color = "white")

# facet_plot
inci %>%  
  rolling_average(before = 2) %>% 
  facet_plot(color = "white")

```
![](https://i.imgur.com/OGtRBR8.png)

![](https://i.imgur.com/T9qNr5x.png)

**Comment by tjtnew** [comment]
closed in cbad41f5b1783f76795676b9907033ee31396ab4

**Comment by aspina7** [comment]
ah sorry - kept forgetting to look at this! 
Yes looks great, think people might be thrown off by the regroup() bit ,... but also not dramatic

**Comment by tjtnew** [comment]
yeah it's a little awkward and why it took me a while thinking about the best approach.  

It's because I wanted the general plot function to work as similarly as possible to normal ggplot commands (e.g. how it deals with fill etc).  Without changing how the plotting function works it's... awkward.  Remove the regroup and you'll see what I mean.  I'll definitely add it as an issue for a later release as it does add a bit of friction to the interface.
