### ISSUE TITLE
Center x-axis annotations by default

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence2#43]
The current default for x-axis annotations is to be left-justified, e.g.:
``` r
library(outbreaks)
library(incidence2)

x <- ebola_sim_clean$linelist %>%
  incidence(date_index = date_of_onset, interval = "month")
plot(x) + scale_x_incidence(x, format = "%d %M %Y")
#> Scale for 'x' is already present. Adding another scale for 'x', which will
#> replace the existing scale.
```

![](https://i.imgur.com/mXD9q3a.png)

I suspect most users will want to center the labels by default. It could be done by adding a `center_labels = TRUE` by default to `scale_x_incidence`, but this argument already exists with a different meaning (position of the tick marks) in the `plot` method. 

One solution would be to:

1. rename `center_labels` to `center_tick` in the plot method
2. add a `center_labels` argument to `scale_x_incidence`

But I am sure there are other options - just can't think of a good one atm.

**Comment by tjtnew** [comment]
closed with the v0.2.0 release https://github.com/reconhub/incidence2/commit/06d70b4511079f5a5abfd127cf7f74984589e4bc. I've renamed `center_labels` to `center_ticks` and fixed a bug so the labels are centrally placed and nicely spaced for facets.
