### ISSUE TITLE
Possible new features: subsetting time windows

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence2#47]
Subsetting objects by given time windows may be one of the only things made slightly easier in the original *incidence* package. For instance, `x[1:5]` would get you the first 5 time steps (days / weeks / months) of the object, which is a little trickier to do now. It would be useful to have some functions helping with this - see some proposed example uses below.

## Filter first / last days / weeks / months etc.

Filter the data to retain the first or last data points, predicated on a duration. There is a question here, as to how duration can be specified:

1. simplest form: duration is provided as `integer` days
2. other simple form: duration is provided as `integer` time intervals (as specified by the bins of the object)
3. interpreted like the 'interval' argument of `incidence2::incidence`, so we could do things like `"3 months"` to have the first 3 months of data (possibly months 1 and 3 not being complete)

Examples would be (depending on the option above we retain):

- `filter_first(x, 30)`: retain the first 30 days of data, or all of it if there are less than 30 days
- `filter_first(x, "1 month")`: retain the first month of data; may not be a full month, only data from the first reported month
- `filter_last(x, "4 weeks")`: retain the last 4 weeks of data; the last week may not be complete e.g. if the last date is a Thursday, so this may not be 28 days of data
- `filter_last(x, 28)`: filters the first 28 days data (irrespective of week definition)

## Subset

We could re-implement the features of `incidence::subset()`, but possibly renaming the function. It would merely be a wrapper for `filter` on dates.

**Comment by tjtnew** [comment]
How about something like this:
``` r
library(outbreaks)
library(incidence2)

dat <- ebola_sim_clean$linelist

inci <- incidence(
  dat,
  date_index = date_of_onset,
  interval = "1 week", 
  groups = gender
)

inci
#> An incidence2 object: 109 x 3
#> [5829 cases from days 2014-W15 to 2015-W18]
#> [interval: 1 week]
#> [cumulative: FALSE]
#> 
#>    date_index gender count
#>    <yrwk>     <fct>  <int>
#>  1 2014-W15   f          1
#>  2 2014-W16   m          1
#>  3 2014-W17   f          4
#>  4 2014-W17   m          1
#>  5 2014-W18   f          4
#>  6 2014-W19   f          9
#>  7 2014-W19   m          3
#>  8 2014-W20   f          7
#>  9 2014-W20   m         10
#> 10 2014-W21   f          8
#> # … with 99 more rows

keep_first(inci, 5)
#> An incidence2 object: 7 x 3
#> [23 cases from days 2014-W15 to 2014-W19]
#> [interval: 1 week]
#> [cumulative: FALSE]
#> 
#>   date_index gender count
#>   <yrwk>     <fct>  <int>
#> 1 2014-W15   f          1
#> 2 2014-W16   m          1
#> 3 2014-W17   f          4
#> 4 2014-W17   m          1
#> 5 2014-W18   f          4
#> 6 2014-W19   f          9
#> 7 2014-W19   m          3
keep_last(inci, 5)
#> An incidence2 object: 10 x 3
#> [199 cases from days 2015-W14 to 2015-W18]
#> [interval: 1 week]
#> [cumulative: FALSE]
#> 
#>    date_index gender count
#>    <yrwk>     <fct>  <int>
#>  1 2015-W14   f         29
#>  2 2015-W14   m         25
#>  3 2015-W15   f         18
#>  4 2015-W15   m         24
#>  5 2015-W16   f         26
#>  6 2015-W16   m         18
#>  7 2015-W17   f         18
#>  8 2015-W17   m         22
#>  9 2015-W18   f         10
#> 10 2015-W18   m          9
```

**Comment by tjtnew** [comment]
closed by https://github.com/reconhub/incidence2/commit/56b26bef37e5418c71f842a734f8548f10758a0d and https://github.com/reconhub/incidence2/commit/687a750433cf9dee4f2ba9c627984ba9a351cdad
