### ISSUE TITLE
Allowing adding non-integer numbers to grate objects

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence2#54]
A maybe not very frequent use case: define limits between two time intervals defined by grate, e.g. to visually delineate epochs in a graph using a vertical line. 

Currently the following will error on purpose:
```r
> as_yrwk("2021-W03") + 1
[1] "2021-W04"

> as_yrwk("2021-W03") + 1.5
Error: Can only add whole numbers to <yrwk> objects
```

But unsure if we want to change this or not.

**Comment by tjtnew** [comment]
This is tricky as currently we transform the data to a better behaved (unit spacing between consecutive date groups) scale within the plotting function.  The solution is to transform the data prior to making the class.  It may actually be better to do this as the underlying representation is likely to be better for the user.  Will start a new branch to explore.

**Comment by tjtnew** [comment]
I think https://github.com/reconhub/incidence2/commit/3f1d2f4f35ed9473754164030bfabf84404269be will enable what I think your use case is with a little hacking (see below).  I'm not sure we want to be any more flexible than this (i.e. allowing hacking if really needed):
``` r
library(outbreaks)
library(incidence2)
library(ggplot2)

res <- incidence(
  covid19_england_nhscalls_2020,
  date_index = date,
  interval = "1 week"
) 
res
#> An incidence2 object: 27 x 2
#> 253670 cases from 2020-W12 to 2020-W38
#> interval: 1 monday week
#> cumulative: FALSE
#> 
#>    date_index count
#>    <yrwk>     <int>
#>  1 2020-W12   12987
#>  2 2020-W13   18263
#>  3 2020-W14   14389
#>  4 2020-W15   11486
#>  5 2020-W16   10058
#>  6 2020-W17   10562
#>  7 2020-W18   11367
#>  8 2020-W19   10846
#>  9 2020-W20   10396
#> 10 2020-W21    9816
#> # … with 17 more rows
xint <- (as.integer(res$date_index[19]) + as.integer(res$date_index[20])) / 2
plot(res) + geom_vline(xintercept = xint)
```

![](https://i.imgur.com/h8n9nPz.png)

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by thibautjombart** [comment]
Looks perfect to me! Agreed re the desired level of flexibility.

**Comment by tjtnew** [comment]
closed with https://github.com/reconhub/incidence2/commit/3f1d2f4f35ed9473754164030bfabf84404269be
