### ISSUE TITLE
Strategy for renaming functions

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/incidence2#8]
For instance, `pool` may be better named `regroup`, and I guess there could be more cases like this. Generally speaking, renaming things from the original `incidence` poses some trade-offs. There are several strategies we may consider:

## Stick to the old
We keep old names as much as possible, and only use new names for new features.

## Scrap the old
As this is a reboot, we can do away with old names, and rely on documentation for people to find out correspondence. A softer version would be to have `incidence2::pool` merely return `NULL` (or an error) and throw a message saying that this feature is now called `regroup` in *incidence2*.

## Aliases
We could have `incidence2::regroup <- incidence2::pool`. If so, do we want to:
* keep aliases going forward (I think not)
* mark old names as deprecated and eventually remove them? It might make sense in terms of transition, but it is weird to develop a new package with already deprecated functions, with a schedule that explicitely plans breaking backward compatibility fruther down the line.

**Comment by thibautjombart** [comment]
I think my personnal preference for now is 'Scrap the old' but add 'messenger' functions for some features, e.g. `incidence2::pool` simply throws a message saying this feature is implemented by `incidence2::regroup`.

**Comment by tjtnew** [comment]
My initial thought was aliases but you make a good point.  Let's go with your suggestion of a message.  Similar to this `incidence` itself does not convey what is happening but `create_incidence` is, maybe, too verbose?

**Comment by thibautjombart** [comment]
I increasingly like verbose but there seems to be a sensible exception for the main feature of a package, e.g. 

* `tibble::tibble` is not `tibble::create_tibble`
* `ggplot2::ggplot` is not `tibble::new_ggplot`

Incidentally (pun) I am never sure whether to use `build_xxx`, `new_xxx`, `create_xxx` or `make_xxx` - though I tend to avoid `new_xxx` as it looks too much like an S4 constructor.
